parameters:
# jobsLists
- name: code # jobsList inserted into code stage in stages
  type: jobList
  default: []
- name: build # jobsList inserted into build stage in stages
  type: jobList
  default: []
- name: deploy # deploymentList inserted into deploy stage in stages
  type: deploymentList
  default: []
- name: test # jobList inserted into test stage in stages
  type: jobList
  default: []
- name: promote # deploymentList inserted into promote stage in stages
  type: deploymentList
  default: []
- name: reject # deploymentList inserted into reject stage in stages
  type: deploymentList
  default: []

# stageList
- name: stages # Inserts each stage into stages
  type: stageList
  default:
  - stage: code # code jobList param inserted to this stage
    dependsOn: []
    condition: and(succeeded(), eq(variables['build.reason'], 'PullRequest'))
  - stage: build # build jobList param inserted to this stage
    dependsOn: code
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger'))
  - stage: deploy # deploy jobList param inserted to this stage
    dependsOn: build
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger', 'Manual'))
  - stage: test # test jobList param inserted to this stage
    dependsOn:
      - build
      - deploy
    condition: succeeded()
  - stage: promote # promote jobList param inserted to this stage
    dependsOn:
      - deploy
      - test
    condition: and(succeeded(), in(variables['build.reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger', 'Manual'))
  - stage: reject
    dependsOn:
      - deploy
      - test
      - promote
    condition: failed()

- name: stagesSuffix # Optional stage name suffix. e.g. Dev would make buildDev, deployDev, etc.
  type: string
  default: ''
- name: stagesPrefix # Optional stage name prefix. e.g. dev- would make dev-build, dev-deploy, etc.
  type: string
  default: ''
- name: stagesCondition # Optional param to override the condition of all stages
  type: string
  default: ''

stages:
# For each stage in stages
- ${{ each stage in parameters.stages }}:
  # If stage name is code, build, deploy, test, or promote, then use jobList or deploymentList with matching name
  - ${{ if in(stage.stage, 'code', 'build', 'deploy', 'test', 'promote', 'reject') }}:
    - ${{ each parameter in parameters }}:
      # If parameter name matches stage name insert parameter for job list in stage
      - ${{ if and(eq(parameter.key, stage.stage), parameter.value) }}:
        - stage: '${{ parameters.stagesPrefix }}${{ stage.stage }}${{ parameters.stagesSuffix }}'
          # If stage in stages param has dependencies insert them
          ${{ if stage.dependsOn }}:
            dependsOn:
              # For each dependency in this stage, only depend on that stage if it has jobs
              - ${{ each dependency in stage.dependsOn }}:
                # If stage depends on code stage and jobs in code param
                - ${{ if and(eq(dependency, 'code'), gt(length(parameters.code), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on build stage and jobs in build param
                - ${{ if and(eq(dependency, 'build'), gt(length(parameters.build), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on deploy stage and jobs in deploy param
                - ${{ if and(eq(dependency, 'deploy'), gt(length(parameters.deploy), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on test stage and jobs in test param
                - ${{ if and(eq(dependency, 'test'), gt(length(parameters.test), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on promote stage and jobs in promote param
                - ${{ if and(eq(dependency, 'promote'), gt(length(parameters.promote), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on reject stage and jobs in reject param
                - ${{ if and(eq(dependency, 'reject'), gt(length(parameters.reject), 0)) }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
                # If stage depends on stages other than code, build, deploy, test, and promote, insert the dependency
                - ${{ if notIn(dependency, 'code', 'build', 'deploy', 'test', 'promote', 'reject') }}:
                  - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
          ${{ if not(stage.dependsOn) }}:
            dependsOn: []
          # If stage in stages param has condition and stagesCondition param has no value set to override, insert the condition
          ${{ if and(stage.condition, not(parameters.stagesCondition)) }}:
            condition: ${{ stage.condition }} 
          # If stagesCondition param has value use it for condition
          ${{ if parameters.stagesCondition }}:
            condition: ${{ parameters.stagesCondition }} 
          # If stage in stages has no condition and stagesCondition param has no value, stage condition defaults to true
          ${{ if and(not(stage.condition), not(parameters.stagesCondition)) }}:
            condition: true
          jobs:
            # Insert each job in jobList or deploymentList parameter
            - ${{ each job in parameter }}:
              - ${{ job }}
            - ${{ if gt(length(stage.jobs), 0) }}:
              # If jobs are nested in stage of stages param insert them
              - ${{ each job in stage.jobs }}:
                - ${{ job }}
  ## Insert any additions stages from stageList
  - ${{ if notIn(stage.stage, 'code', 'build', 'deploy', 'test', 'promote', 'reject') }}:
    - stage: '${{ parameters.stagesPrefix }}${{ stage.stage }}${{ parameters.stagesSuffix }}'
      # If stage in stages param has dependencies insert them
      ${{ if stage.dependsOn }}:
        dependsOn:
          # For each dependency in this stage, only depend on that stage if it has jobs
          - ${{ each dependency in stage.dependsOn }}:
            # If stage depends on code stage and jobs in code param
            - ${{ if and(eq(dependency, 'code'), gt(length(parameters.code), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on build stage and jobs in build param
            - ${{ if and(eq(dependency, 'build'), gt(length(parameters.build), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on deploy stage and jobs in deploy param
            - ${{ if and(eq(dependency, 'deploy'), gt(length(parameters.deploy), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on test stage and jobs in test param
            - ${{ if and(eq(dependency, 'test'), gt(length(parameters.test), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on promote stage and jobs in promote param
            - ${{ if and(eq(dependency, 'promote'), gt(length(parameters.promote), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on reject stage and jobs in reject param
            - ${{ if and(eq(dependency, 'reject'), gt(length(parameters.reject), 0)) }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
            # If stage depends on stages other than code, build, deploy, test, promote, and reject, insert the dependency
            - ${{ if notIn(dependency, 'code', 'build', 'deploy', 'test', 'promote', 'reject') }}:
              - '${{ parameters.stagesPrefix }}${{ dependency }}${{ parameters.stagesSuffix }}'
      ${{ if not(stage.dependsOn) }}:
        dependsOn: []
      # If stage in stages param has condition and stagesCondition param has no value set to override, insert the condition
      ${{ if and(stage.condition, not(parameters.stagesCondition)) }}:
        condition: ${{ stage.condition }} 
      # If stagesCondition param has value use it for condition
      ${{ if parameters.stagesCondition }}:
        condition: ${{ parameters.stagesCondition }} 
      # If stage in stages has no condition and stagesCondition param has no value, stage condition defaults to true
      ${{ if and(not(stage.condition), not(parameters.stagesCondition)) }}:
        condition: true
      jobs:
        - ${{ each job in stage.jobs }}:
          - ${{ job }}
