parameters:
# jobsLists
- name: code # jobsList inserted into codeAnalysis stage in codeStages
  type: jobList
  default: []
- name: build # jobsList inserted into devBuild stage in devStages
  type: jobList
  default: []
- name: deploy # deploymentList inserted into devDeploy stage in devStages
  type: deploymentList
  default: []
- name: promote # deploymentList inserted into devPromote stage in devStages
  type: deploymentList
  default: []
- name: test # jobList inserted into devTests stage in devStages
  type: jobList
  default: []

- name: stages # Inserts each stage into stages
  type: stageList
  default:
  - stage: code # code jobList param inserted to this stage
    dependsOn: []
    condition: succeeded()
  - stage: build # build jobList param inserted to this stage
    dependsOn: code
    condition: succeeded()
  - stage: deploy # deploy jobList param inserted to this stage
    dependsOn: build
    condition: succeeded()
  - stage: promote # promote jobList param inserted to this stage
    dependsOn: deploy
    condition: succeeded()
  - stage: test # test jobList param inserted to this stage
    dependsOn: promote
    condition: succeeded()

stages:
- template: ../stages.yaml
  parameters:
    code: ${{ parameters.code }}
    build: ${{ parameters.build }}
    deploy: ${{ parameters.deploy }}
    promote: ${{ parameters.promote }}
    test: ${{ parameters.test }}
    stages:
    ${{ each stage in parameters.stages }}:
      # If code stage in stages param and jobs in code param 
      ${{ if and(eq(stage.stage, 'code'), gt(length(parameters.code), 0)) }}:
        stage: ${{ stage.stage }}
        ${{ if stage.dependsOn }}:
          dependsOn: ${{ stage.dependsOn }}
        ${{ if stage.condition }}:
          condition: ${{ stage.condition }}
      # If build stage in stages param and jobs in build param 
      ${{ if and(eq(stage.stage, 'build'), gt(length(parameters.build), 0)) }}:
        stage: ${{ stage.stage }}
        ${{ if stage.dependsOn }}:
          dependsOn:
            - ${{ each depends in stage.dependsOn }}:
              # If build stage depends on code stage and jobs in code param
              - ${{ if and(eq(depends, 'code'), gt(length(parameters.code), 0)) }}:
                - ${{ depends }}
              - ${{ if ne(depends, 'code') }}:
                - ${{ depends }}
        ${{ if stage.condition }}:
          condition: ${{ stage.condition }}
      # If deploy stage in stages param and jobs in deploy param 
      ${{ if and(eq(stage.stage, 'deploy'), gt(length(parameters.deploy), 0)) }}:
        stage: ${{ stage.stage }}
        ${{ if stage.dependsOn }}:
          dependsOn:
            - ${{ each depends in stage.dependsOn }}:
              # If deploy stage depends on code stage and jobs in code param
              - ${{ if and(eq(depends, 'code'), gt(length(parameters.code), 0)) }}:
                - ${{ depends }}
              # If deploy stage depends on build stage and jobs in build param
              - ${{ if and(eq(depends, 'build'), gt(length(parameters.build), 0)) }}:
                - ${{ depends }}
              - ${{ if not(in(depends, 'code', 'build')) }}:
                - ${{ depends }}
        ${{ if stage.condition }}:
          condition: ${{ stage.condition }} 
        jobs:
          ${{ parameters.deploy }}
      # If promote stage in stages param and jobs in promote param 
      ${{ if and(eq(stage.stage, 'promote'), gt(length(parameters.promote), 0)) }}:
        stage: ${{ stage.stage }}
        ${{ if stage.dependsOn }}:
          dependsOn:
            - ${{ each depends in stage.dependsOn }}:
              # If promote stage depends on code stage and jobs in code param
              - ${{ if and(eq(depends, 'code'), gt(length(parameters.code), 0)) }}:
                - ${{ depends }}
              # If promote stage depends on build stage and jobs in build param
              - ${{ if and(eq(depends, 'build'), gt(length(parameters.build), 0)) }}:
                - ${{ depends }}
              # If promote stage depends on deploy stage and jobs in deploy param
              - ${{ if and(eq(depends, 'deploy'), gt(length(parameters.deploy), 0)) }}:
                - ${{ depends }}
              - ${{ if not(in(depends, 'code', 'build', 'deploy')) }}:
                - ${{ depends }}
        ${{ if stage.condition }}:
          condition: ${{ stage.condition }} 
        jobs:
          ${{ parameters.promote }}
      ${{ if and(eq(stage.stage, 'test'), gt(length(parameters.tests), 0)) }}:
        stage: ${{ stage.stage }}
        ${{ if stage.dependsOn }}:
          dependsOn:
            - ${{ each depends in stage.dependsOn }}:
              # If test stage depends on code stage and jobs in code param
              - ${{ if and(eq(depends, 'code'), gt(length(parameters.code), 0)) }}:
                - ${{ depends }}
              # If test stage depends on build stage and jobs in build param
              - ${{ if and(eq(depends, 'build'), gt(length(parameters.build), 0)) }}:
                - ${{ depends }}
              # If test stage depends on deploy stage and jobs in deploy param
              - ${{ if and(eq(depends, 'deploy'), gt(length(parameters.deploy), 0)) }}:
                - ${{ depends }}
              # If test stage depends on promote stage and jobs in promote param
              - ${{ if and(eq(depends, 'promote'), gt(length(parameters.promote), 0)) }}:
                - ${{ depends }}
              - ${{ if not(in(depends, 'code', 'build', 'deploy', 'promote')) }}:
                - ${{ depends }}
        ${{ if stage.condition }}:
          condition: ${{ stage.condition }} 
        jobs:
          ${{ parameters.test }}
    ## Insert any additions stages from stageList
    ${{ if not(in(stage.stage, 'code', 'build', 'deploy', 'promote', 'test')) }}:
      ${{ stage }}
