# This pipeline is to test the syntax of the stages.yaml and stages-stepLists.yaml templates
name: $(Build.DefinitionName)_$(Build.SourceVersion)_$(Build.SourceBranchName) # name is the format for $(Build.BuildNumber)

resources:
  repositories:
    - repository: blazor
      type: github
      name: fitchtech/BlazorServerApp
      ref: refs/heads/master
      endpoint: GitHub
      trigger: none

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v1*

extends:
  template: ../presets/stages-jobTypes.yaml
  parameters:
    timeoutInMinutes: 5
    cancelTimeoutInMinutes: 1
    containerRegistry: DockerHub
    dockerBuilds:
      - job: containerImage
        checkout: blazor
        dockerFile: BlazorServerApp/Dockerfile
        dockerTags: ${{ lower(variables['Build.BuildNumber']) }}
        containerRepository: blazor
