# This pipeline is to test the syntax of the stages.yaml and stages-stepLists.yaml templates
name: $[lower(variables['System.DefinitionId'])_lower(variables['Build.SourceVersion'])_lower(variables['Build.SourceBranchName'])] # name is the format for $(Build.BuildNumber)

resources:
  repositories:
    - repository: blazor
      type: github
      name: fitchtech/BlazorServerApp
      ref: refs/heads/master
      endpoint: GitHub
      trigger: none

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v1*

extends:
  template: ../presets/stages-jobTypes.yaml
  parameters:
    timeoutInMinutes: 1
    cancelTimeoutInMinutes: 1
    containerRegistry: DockerHub
    dockerBuilds:
      - job: containerImage
        checkout: blazor
        dockerFile: BlazorServerApp/Dockerfile
        containerRepository: blazor
